from django.urls import path

from apps.course.views import (
    CourseArchiveAPIView,
    CourseAssignmentDetailAPIView,
    CourseAssignmentListCreateAPIView,
    CourseDetailAPIView,
    CourseDuplicateAPIView,
    CourseEnrollmentCancelAPIView,
    CourseEnrollmentDetailAPIView,
    CourseEnrollmentListAPIView,
    CourseEnrollmentStartAPIView,
    CourseLessonDetailAPIView,
    CourseLessonListCreateAPIView,
    CourseLessonMoveAPIView,
    CourseLessonReorderAPIView,
    CourseMaterialDetailAPIView,
    CourseMaterialListCreateAPIView,
    CourseModuleDetailAPIView,
    CourseModuleListCreateAPIView,
    CourseModuleReorderAPIView,
    CourseProgressDetailAPIView,
    CourseProgressListAPIView,
    CoursePublicDetailAPIView,
    CoursePublicListAPIView,
    CoursePublishAPIView,
    CourseTeacherDetailAPIView,
    CourseTeacherListCreateAPIView,
    CourseListCreateAPIView,
    LessonProgressCompleteAPIView,
    LessonProgressListAPIView,
    LessonProgressMarkInProgressAPIView,
    MyCourseEnrollmentListAPIView,
)

app_name = "course"

urlpatterns = [
    path(
        "courses/",
        CourseListCreateAPIView.as_view(),
        name="course-list-create",
    ),
    path(
        "courses/public/",
        CoursePublicListAPIView.as_view(),
        name="course-public-list",
    ),
    path(
        "courses/public/<int:pk>/",
        CoursePublicDetailAPIView.as_view(),
        name="course-public-detail",
    ),
    path(
        "courses/<int:pk>/",
        CourseDetailAPIView.as_view(),
        name="course-detail",
    ),
    path(
        "courses/<int:pk>/publish/",
        CoursePublishAPIView.as_view(),
        name="course-publish",
    ),
    path(
        "courses/<int:pk>/archive/",
        CourseArchiveAPIView.as_view(),
        name="course-archive",
    ),
    path(
        "courses/<int:pk>/duplicate/",
        CourseDuplicateAPIView.as_view(),
        name="course-duplicate",
    ),
    path(
        "courses/<int:pk>/teachers/",
        CourseTeacherListCreateAPIView.as_view(),
        name="course-teacher-list-create",
    ),
    path(
        "courses/<int:course_pk>/teachers/<int:teacher_link_pk>/",
        CourseTeacherDetailAPIView.as_view(),
        name="course-teacher-detail",
    ),
    path(
        "courses/<int:course_pk>/modules/",
        CourseModuleListCreateAPIView.as_view(),
        name="course-module-list-create",
    ),
    path(
        "courses/<int:course_pk>/modules/reorder/",
        CourseModuleReorderAPIView.as_view(),
        name="course-module-reorder",
    ),
    path(
        "modules/<int:module_pk>/",
        CourseModuleDetailAPIView.as_view(),
        name="course-module-detail",
    ),
    path(
        "modules/<int:module_pk>/lessons/",
        CourseLessonListCreateAPIView.as_view(),
        name="course-lesson-list-create",
    ),
    path(
        "modules/<int:module_pk>/lessons/reorder/",
        CourseLessonReorderAPIView.as_view(),
        name="course-lesson-reorder",
    ),
    path(
        "lessons/<int:lesson_pk>/",
        CourseLessonDetailAPIView.as_view(),
        name="course-lesson-detail",
    ),
    path(
        "lessons/<int:lesson_pk>/move/",
        CourseLessonMoveAPIView.as_view(),
        name="course-lesson-move",
    ),
    path(
        "courses/<int:course_pk>/materials/",
        CourseMaterialListCreateAPIView.as_view(),
        name="course-material-list-create",
    ),
    path(
        "materials/<int:material_pk>/",
        CourseMaterialDetailAPIView.as_view(),
        name="course-material-detail",
    ),
    path(
        "courses/<int:course_pk>/assignments/",
        CourseAssignmentListCreateAPIView.as_view(),
        name="course-assignment-list-create",
    ),
    path(
        "assignments/<int:assignment_pk>/",
        CourseAssignmentDetailAPIView.as_view(),
        name="course-assignment-detail",
    ),
    path(
        "courses/<int:course_pk>/enrollments/",
        CourseEnrollmentListAPIView.as_view(),
        name="course-enrollment-list",
    ),
    path(
        "enrollments/my/",
        MyCourseEnrollmentListAPIView.as_view(),
        name="my-course-enrollment-list",
    ),
    path(
        "enrollments/<int:enrollment_pk>/",
        CourseEnrollmentDetailAPIView.as_view(),
        name="course-enrollment-detail",
    ),
    path(
        "enrollments/<int:enrollment_pk>/cancel/",
        CourseEnrollmentCancelAPIView.as_view(),
        name="course-enrollment-cancel",
    ),
    path(
        "enrollments/<int:enrollment_pk>/start/",
        CourseEnrollmentStartAPIView.as_view(),
        name="course-enrollment-start",
    ),
    path(
        "progress/",
        CourseProgressListAPIView.as_view(),
        name="course-progress-list",
    ),
    path(
        "progress/<int:enrollment_pk>/",
        CourseProgressDetailAPIView.as_view(),
        name="course-progress-detail",
    ),
    path(
        "enrollments/<int:enrollment_pk>/lesson-progress/",
        LessonProgressListAPIView.as_view(),
        name="lesson-progress-list",
    ),
    path(
        "enrollments/<int:enrollment_pk>/lessons/<int:lesson_pk>/in-progress/",
        LessonProgressMarkInProgressAPIView.as_view(),
        name="lesson-progress-in-progress",
    ),
    path(
        "enrollments/<int:enrollment_pk>/lessons/<int:lesson_pk>/complete/",
        LessonProgressCompleteAPIView.as_view(),
        name="lesson-progress-complete",
    ),
]
