# Generated by Django 6.0.3 on 2026-04-19 14:26

import apps.users.models.user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Системные роли: admin, teacher, student, parent.', max_length=10, unique=True, verbose_name='Код роли')),
                ('name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'users_roles',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Основная эл.почта')),
                ('reset_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Резервная почта для восстановления')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Почта подтверждена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Доступ в административную панель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users_user',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.users.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=255, verbose_name='Род деятельности')),
                ('work_place', models.CharField(blank=True, max_length=255, verbose_name='Место работы')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32, verbose_name='Экстренный телефон для связи')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Служебные заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль родителя',
                'verbose_name_plural': 'Профили родителей',
                'db_table': 'users_parent_profile',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('not_specified', 'Не указан')], default='not_specified', max_length=20, verbose_name='Пол')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Аватар')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='Город')),
                ('timezone', models.CharField(blank=True, default='Europe/Moscow', max_length=150, verbose_name='Часовой пояс')),
                ('social_link_max', models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль в мессенджер MAX')),
                ('social_link_vk', models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль в ВКонтакте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'users_profile',
                'ordering': ('last_name', 'first_name', 'patronymic'),
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(blank=True, help_text='Внутренний код студента в обр.организации, зависит от группы. Например: ИП-4-01', max_length=64, verbose_name='Код студента')),
                ('admission_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год постпуления')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('academic_lead', 'Академический отпуск'), ('tramsferred', 'Переведен'), ('graduated', 'Выпустился'), ('archived', 'В архиве')], default='active', max_length=32, verbose_name='Статус студента')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Служебные заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студентов',
                'db_table': 'users_student_profile',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_title', models.CharField(blank=True, help_text='Например: "Преподаватель математики".', max_length=255, verbose_name='Публичный заголовок')),
                ('short_bio', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('experience', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Стаж (лет)')),
                ('achievements', models.TextField(blank=True, help_text='Короткий блок достижений для карточки преподавателя.', verbose_name='Краткое описание достижений и наград')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='users/teachers/covers/', verbose_name='Обложка карточки преподавателя')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный профиль')),
                ('show_on_teachers_page', models.BooleanField(default=True, verbose_name='Показывать на странице преподавателей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль преподавателя',
                'verbose_name_plural': 'Профили преподавателей',
                'db_table': 'users_teacher_profile',
            },
        ),
        migrations.CreateModel(
            name='ParentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('guardian', 'Опекун'), ('representative', 'Законный представитель'), ('other', 'Иное')], default='other', max_length=20, verbose_name='Тип связи')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной представитель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_student_links', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_parent_links', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Связь родитель-студент',
                'verbose_name_plural': 'Связи родитель-студент',
                'db_table': 'users_parent_student_links',
                'ordering': ('-is_primary', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('parent', 'student'), name='unique_parent_student_links')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователя',
                'db_table': 'users_user_role',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role')],
            },
        ),
    ]
