# Generated by Django 6.0.3 on 2026-04-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parentstudent',
            name='unique_parent_student_links',
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='relation_type',
            field=models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('guardian', 'Опекун'), ('representative', 'Законный представитель'), ('other', 'Иное')], default='other', max_length=32, verbose_name='Тип связи'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('not_specified', 'Не указан')], default='not_specified', max_length=32, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_link_max',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль в мессенджере MAX'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_link_vk',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль во ВКонтакте'),
        ),
        migrations.AddConstraint(
            model_name='parentstudent',
            constraint=models.UniqueConstraint(fields=('parent', 'student'), name='unique_parent_student_link'),
        ),
        migrations.AlterModelTable(
            name='parentstudent',
            table='users_parent_student',
        ),
        migrations.RemoveField(
            model_name='parentstudent',
            name='updated_at',
        ),
    ]
