# Generated by Django 6.0.4 on 2026-04-20 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0002_remove_parentstudent_unique_parent_student_links_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentstudent',
            options={'verbose_name': 'Связь родителя и студента', 'verbose_name_plural': 'Связи родителей и студентов'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at', 'email'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='is_public',
            new_name='is_public_profile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_email_verified',
            new_name='is_email_verify',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='public_title',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='short_bio',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='show_on_teachers_page',
        ),
        migrations.AddField(
            model_name='parentstudent',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='parentstudent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_parent_student_links', to=settings.AUTH_USER_MODEL, verbose_name='Кем подтверждено'),
        ),
        migrations.AddField(
            model_name='parentstudent',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='parentstudent',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_parent_student_links', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан запрос'),
        ),
        migrations.AddField(
            model_name='parentstudent',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('revoked', 'Отозвано')], db_index=True, default='pending', max_length=20, verbose_name='Статус связи'),
        ),
        migrations.AddField(
            model_name='parentstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='requested_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to='organizations.department', verbose_name='Запрошенное отделение'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='requested_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to='organizations.group', verbose_name='Запрошенная группа'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='requested_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to='organizations.organization', verbose_name='Запрошенная образовательная организация'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='submitted_group_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='Введённый код группы'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verification_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий по верификации'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verification_status',
            field=models.CharField(choices=[('not_filled', 'Не заполнено'), ('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], db_index=True, default='not_filled', max_length=20, verbose_name='Статус верификации'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_student_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Кем подтверждено'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='code_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения кода приглашения'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='education_info',
            field=models.TextField(blank=True, default='', verbose_name='Сведения об образовании'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='employee_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Служебный код сотрудника'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Стаж в годах'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='requested_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_requests', to='organizations.department', verbose_name='Запрошенное отделение'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='requested_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_requests', to='organizations.organization', verbose_name='Запрошенная образовательная организация'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='verification_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий по верификации'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='verification_status',
            field=models.CharField(choices=[('not_verified', 'Не подтверждено'), ('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], db_index=True, default='not_verified', max_length=20, verbose_name='Статус верификации'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончательной верификации'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_teacher_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Кем подтверждено'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения онбординга'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает подтверждения'), ('active', 'Активирован'), ('rejected', 'Отклонён'), ('blocked', 'Заблокирован')], db_index=True, default='draft', max_length=20, verbose_name='Статус онбординга'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_type',
            field=models.CharField(choices=[('student', 'Студент'), ('parent', 'Родитель'), ('teacher', 'Преподаватель')], db_index=True, default='student', max_length=20, verbose_name='Тип регистрации'),
        ),
        migrations.AddField(
            model_name='user',
            name='review_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий по проверке'),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки заявки'),
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основная связь'),
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL, verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='relation_type',
            field=models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('guardian', 'Опекун'), ('trustee', 'Попечитель'), ('other', 'Иное')], default='other', max_length=20, verbose_name='Тип связи'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год поступления'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Внутренний код студента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Основная эл. почта'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
