# Generated by Django 6.0.4 on 2026-04-21 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0003_alter_parentstudent_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentstudent',
            options={'ordering': ('-is_primary', '-created_at'), 'verbose_name': 'Связь родитель-студент', 'verbose_name_plural': 'Связи родитель-студент'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='is_public_profile',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_email_verify',
            new_name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='parentstudent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='education_info',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='employee_code',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='position',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('academic_lead', 'Академический отпуск'), ('tramsferred', 'Переведен'), ('graduated', 'Выпустился'), ('archived', 'В архиве')], default='active', max_length=32, verbose_name='Статус студента'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='achievements',
            field=models.TextField(blank=True, help_text='Короткий блок достижений для карточки преподавателя.', verbose_name='Краткое описание достижений и наград'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/teachers/covers/', verbose_name='Обложка карточки преподавателя'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='education',
            field=models.TextField(blank=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Стаж (лет)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='public_title',
            field=models.CharField(blank=True, help_text='Например: "Преподаватель математики".', max_length=255, verbose_name='Публичный заголовок'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='short_bio',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='show_on_teachers_page',
            field=models.BooleanField(default=True, verbose_name='Показывать на странице преподавателей'),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_users', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_parent_student_links', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил'),
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основной представитель'),
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_student_links', to=settings.AUTH_USER_MODEL, verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='relation_type',
            field=models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('guardian', 'Опекун'), ('representative', 'Законный представитель'), ('other', 'Иное')], default='other', max_length=32, verbose_name='Тип связи'),
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_parent_student_links', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор запроса'),
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('revoked', 'Отозвано')], default='pending', max_length=32, verbose_name='Статус связи'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год постпуления'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Служебные заметки'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='requested_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile_requests', to='organizations.department', verbose_name='Запрошенное отделение'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='requested_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile_requests', to='organizations.group', verbose_name='Запрошенная группа'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='requested_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile_requests', to='organizations.organization', verbose_name='Запрошенная образовательная организация'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_code',
            field=models.CharField(blank=True, help_text='Внутренний код студента в обр.организации, зависит от группы. Например: ИП-4-01', max_length=64, verbose_name='Код студента'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='submitted_group_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='Введенный код группы'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='verification_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий проверки'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='verification_status',
            field=models.CharField(choices=[('not_filled', 'Не заполнено'), ('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='not_filled', max_length=32, verbose_name='Статус подтверждения'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_student_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='code_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения регистрационного кода'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='requested_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile_requests', to='organizations.department', verbose_name='Запрошенное подразделение'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='requested_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile_requests', to='organizations.organization', verbose_name='Запрошенная образовательная организация'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='verification_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий проверки'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='verification_status',
            field=models.CharField(choices=[('not_verified', 'Не подтвержден'), ('pending', 'Ожидает подтверждения'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='not_verified', max_length=32, verbose_name='Статус подтверждения'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончательного подтверждения'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_teacher_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Основная эл.почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='onboarding_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает подтверждения'), ('active', 'Активирован'), ('rejected', 'Отклонен'), ('blocked', 'Заблокирован')], default='draft', max_length=32, verbose_name='Статус онбординга'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_type',
            field=models.CharField(choices=[('unknown', 'Не указан'), ('student', 'Студент'), ('parent', 'Родитель'), ('teacher', 'Преподаватель')], default='unknown', max_length=32, verbose_name='Тип регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий проверки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
