# Generated by Django 5.0.7 on 2026-05-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_parentstudent_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Служебные заметки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_link_max',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на профиль в мессенджере MAX'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_link_vk',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на профиль во ВКонтакте'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Служебные заметки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Резервная почта для восстановления'),
            preserve_default=False,
        ),
    ]
