from __future__ import annotations

from django.utils.translation import gettext_lazy as _


ROLE_ADMIN = "admin"
ROLE_TEACHER = "teacher"
ROLE_STUDENT = "student"
ROLE_PARENT = "parent"

SYSTEM_ROLE_CODES = (
    ROLE_ADMIN,
    ROLE_TEACHER,
    ROLE_STUDENT,
    ROLE_PARENT,
)

SYSTEM_ROLE_NAMES = {
    ROLE_ADMIN: _("Администратор"),
    ROLE_TEACHER: _("Преподаватель"),
    ROLE_STUDENT: _("Студент"),
    ROLE_PARENT: _("Родитель"),
}

PRIVILEGED_ROLE_CODES = (
    ROLE_ADMIN,
    ROLE_TEACHER,
)

REGISTRATION_TYPE_STUDENT = "student"
REGISTRATION_TYPE_PARENT = "parent"
REGISTRATION_TYPE_TEACHER = "teacher"

REGISTRATION_TYPE_CHOICES = (
    REGISTRATION_TYPE_STUDENT,
    REGISTRATION_TYPE_PARENT,
    REGISTRATION_TYPE_TEACHER,
)

ONBOARDING_STATUS_DRAFT = "draft"
ONBOARDING_STATUS_PENDING = "pending"
ONBOARDING_STATUS_ACTIVE = "active"
ONBOARDING_STATUS_REJECTED = "rejected"
ONBOARDING_STATUS_BLOCKED = "blocked"

ONBOARDING_STATUS_CHOICES = (
    ONBOARDING_STATUS_DRAFT,
    ONBOARDING_STATUS_PENDING,
    ONBOARDING_STATUS_ACTIVE,
    ONBOARDING_STATUS_REJECTED,
    ONBOARDING_STATUS_BLOCKED,
)

VERIFICATION_STATUS_NOT_FILLED = "not_filled"
VERIFICATION_STATUS_NOT_VERIFIED = "not_verified"
VERIFICATION_STATUS_PENDING = "pending"
VERIFICATION_STATUS_APPROVED = "approved"
VERIFICATION_STATUS_REJECTED = "rejected"

VERIFICATION_STATUS_CHOICES = (
    VERIFICATION_STATUS_NOT_FILLED,
    VERIFICATION_STATUS_NOT_VERIFIED,
    VERIFICATION_STATUS_PENDING,
    VERIFICATION_STATUS_APPROVED,
    VERIFICATION_STATUS_REJECTED,
)

LINK_STATUS_PENDING = "pending"
LINK_STATUS_APPROVED = "approved"
LINK_STATUS_REJECTED = "rejected"
LINK_STATUS_REVOKED = "revoked"

LINK_STATUS_CHOICES = (
    LINK_STATUS_PENDING,
    LINK_STATUS_APPROVED,
    LINK_STATUS_REJECTED,
    LINK_STATUS_REVOKED,
)

MAX_NAME_LENGTH = 255
MAX_PHONE_NUMBER = 32
MAX_STUDENT_CODE_LENGTH = 64
MAX_EMPLOYEE_CODE_LENGTH = 64
MAX_GROUP_CODE_LENGTH = 128
MAX_REVIEW_COMMENT_LENGTH = 1000
