from __future__ import annotations

from django.urls import path

from apps.assignments.views import (
    AssignmentArchiveAPIView,
    AssignmentAttachmentDetailAPIView,
    AssignmentAttachmentListCreateAPIView,
    AssignmentAudienceListCreateAPIView,
    AssignmentDetailAPIView,
    AssignmentDuplicateAPIView,
    AssignmentListCreateAPIView,
    AssignmentPublicationArchiveAPIView,
    AssignmentPublicationCloseAPIView,
    AssignmentPublicationDetailAPIView,
    AssignmentPublicationListCreateAPIView,
    AssignmentPublicationPublishAPIView,
    AssignmentPublishAPIView,
    AssignmentQuestionDetailAPIView,
    AssignmentQuestionListCreateAPIView,
    AssignmentQuestionReorderAPIView,
    AssignmentSectionDetailAPIView,
    AssignmentSectionListCreateAPIView,
    AssignmentSectionReorderAPIView,
    AssignmentStatisticsAPIView,
    AssignmentVariantDetailAPIView,
    AssignmentVariantListCreateAPIView,
    AssignmentVariantReorderAPIView,
    CourseAssignmentDashboardAPIView,
    GradeRecordCreateFromSubmissionAPIView,
    GradeRecordDetailAPIView,
    GradeRecordListAPIView,
    PublicationStatisticsAPIView,
    ReviewCommentCreateAPIView,
    RubricCriteriaReorderAPIView,
    RubricCriterionDetailAPIView,
    RubricCriterionListCreateAPIView,
    RubricDetailAPIView,
    RubricListCreateAPIView,
    StudentAssignmentProgressAPIView,
    SubmissionAnswerReviewAPIView,
    SubmissionAnswerSaveAPIView,
    SubmissionAttachFileAPIView,
    SubmissionDetailAPIView,
    SubmissionListAPIView,
    SubmissionRetryAPIView,
    SubmissionReviewApproveAPIView,
    SubmissionReviewDetailAPIView,
    SubmissionReviewListAPIView,
    SubmissionReviewRejectAPIView,
    SubmissionReviewReturnForRevisionAPIView,
    SubmissionReviewStartAPIView,
    SubmissionReviewSubmitAPIView,
    SubmissionStartAPIView,
    SubmissionSubmitAPIView,
)

app_name = "assignments"

urlpatterns = [
    path(
        "assignments/",
        AssignmentListCreateAPIView.as_view(),
        name="assignment-list-create",
    ),
    path(
        "assignments/<int:pk>/",
        AssignmentDetailAPIView.as_view(),
        name="assignment-detail",
    ),
    path(
        "assignments/<int:pk>/publish/",
        AssignmentPublishAPIView.as_view(),
        name="assignment-publish",
    ),
    path(
        "assignments/<int:pk>/archive/",
        AssignmentArchiveAPIView.as_view(),
        name="assignment-archive",
    ),
    path(
        "assignments/<int:pk>/duplicate/",
        AssignmentDuplicateAPIView.as_view(),
        name="assignment-duplicate",
    ),

    path(
        "assignments/<int:assignment_id>/variants/",
        AssignmentVariantListCreateAPIView.as_view(),
        name="assignment-variant-list-create",
    ),
    path(
        "variants/<int:pk>/",
        AssignmentVariantDetailAPIView.as_view(),
        name="assignment-variant-detail",
    ),
    path(
        "assignments/<int:assignment_id>/variants/reorder/",
        AssignmentVariantReorderAPIView.as_view(),
        name="assignment-variant-reorder",
    ),

    path(
        "assignments/<int:assignment_id>/sections/",
        AssignmentSectionListCreateAPIView.as_view(),
        name="assignment-section-list-create",
    ),
    path(
        "sections/<int:pk>/",
        AssignmentSectionDetailAPIView.as_view(),
        name="assignment-section-detail",
    ),
    path(
        "assignments/<int:assignment_id>/sections/reorder/",
        AssignmentSectionReorderAPIView.as_view(),
        name="assignment-section-reorder",
    ),

    path(
        "assignments/<int:assignment_id>/questions/",
        AssignmentQuestionListCreateAPIView.as_view(),
        name="assignment-question-list-create",
    ),
    path(
        "questions/<int:pk>/",
        AssignmentQuestionDetailAPIView.as_view(),
        name="assignment-question-detail",
    ),
    path(
        "assignments/<int:assignment_id>/questions/reorder/",
        AssignmentQuestionReorderAPIView.as_view(),
        name="assignment-question-reorder",
    ),

    path(
        "sections/<int:section_id>/questions/",
        AssignmentQuestionListCreateAPIView.as_view(),
        name="section-question-list-create",
    ),
    path(
        "sections/<int:section_id>/questions/reorder/",
        AssignmentQuestionReorderAPIView.as_view(),
        name="section-question-reorder",
    ),

    path(
        "assignments/<int:assignment_id>/attachments/",
        AssignmentAttachmentListCreateAPIView.as_view(),
        name="assignment-attachment-list-create",
    ),
    path(
        "attachments/<int:pk>/",
        AssignmentAttachmentDetailAPIView.as_view(),
        name="assignment-attachment-detail",
    ),

    path(
        "publications/",
        AssignmentPublicationListCreateAPIView.as_view(),
        name="assignment-publication-list-create",
    ),
    path(
        "publications/<int:pk>/",
        AssignmentPublicationDetailAPIView.as_view(),
        name="assignment-publication-detail",
    ),
    path(
        "publications/<int:pk>/publish/",
        AssignmentPublicationPublishAPIView.as_view(),
        name="assignment-publication-publish",
    ),
    path(
        "publications/<int:pk>/close/",
        AssignmentPublicationCloseAPIView.as_view(),
        name="assignment-publication-close",
    ),
    path(
        "publications/<int:pk>/archive/",
        AssignmentPublicationArchiveAPIView.as_view(),
        name="assignment-publication-archive",
    ),
    path(
        "publications/<int:publication_id>/audiences/",
        AssignmentAudienceListCreateAPIView.as_view(),
        name="assignment-audience-list-create",
    ),

    path(
        "submissions/",
        SubmissionListAPIView.as_view(),
        name="submission-list",
    ),
    path(
        "submissions/<int:pk>/",
        SubmissionDetailAPIView.as_view(),
        name="submission-detail",
    ),
    path(
        "submissions/start/",
        SubmissionStartAPIView.as_view(),
        name="submission-start",
    ),
    path(
        "submissions/<int:submission_id>/answers/",
        SubmissionAnswerSaveAPIView.as_view(),
        name="submission-answer-save",
    ),
    path(
        "submissions/<int:submission_id>/attachments/",
        SubmissionAttachFileAPIView.as_view(),
        name="submission-attach-file",
    ),
    path(
        "submissions/<int:submission_id>/submit/",
        SubmissionSubmitAPIView.as_view(),
        name="submission-submit",
    ),
    path(
        "submissions/<int:submission_id>/retry/",
        SubmissionRetryAPIView.as_view(),
        name="submission-retry",
    ),

    path(
        "submissions/<int:submission_id>/reviews/",
        SubmissionReviewListAPIView.as_view(),
        name="submission-review-list",
    ),
    path(
        "reviews/<int:pk>/",
        SubmissionReviewDetailAPIView.as_view(),
        name="submission-review-detail",
    ),
    path(
        "submissions/<int:submission_id>/reviews/start/",
        SubmissionReviewStartAPIView.as_view(),
        name="submission-review-start",
    ),
    path(
        "answers/<int:answer_id>/review/",
        SubmissionAnswerReviewAPIView.as_view(),
        name="submission-answer-review",
    ),

    path(
        "reviews/<int:review_id>/comments/",
        ReviewCommentCreateAPIView.as_view(),
        name="review-comment-create",
    ),

    # Старый вариант оставляем под другим именем.
    path(
        "reviews/comments/",
        ReviewCommentCreateAPIView.as_view(),
        name="review-comment-create-flat",
    ),

    path(
        "reviews/<int:review_id>/submit/",
        SubmissionReviewSubmitAPIView.as_view(),
        name="submission-review-submit",
    ),
    path(
        "reviews/<int:review_id>/return/",
        SubmissionReviewReturnForRevisionAPIView.as_view(),
        name="submission-review-return",
    ),
    path(
        "reviews/<int:review_id>/approve/",
        SubmissionReviewApproveAPIView.as_view(),
        name="submission-review-approve",
    ),
    path(
        "reviews/<int:review_id>/reject/",
        SubmissionReviewRejectAPIView.as_view(),
        name="submission-review-reject",
    ),

    path(
        "rubrics/",
        RubricListCreateAPIView.as_view(),
        name="rubric-list-create",
    ),

    # Совместимость: рубрики конкретной работы.
    path(
        "assignments/<int:assignment_id>/rubrics/",
        RubricListCreateAPIView.as_view(),
        name="assignment-rubric-list-create",
    ),

    path(
        "rubrics/<int:pk>/",
        RubricDetailAPIView.as_view(),
        name="rubric-detail",
    ),
    path(
        "rubrics/<int:rubric_id>/criteria/",
        RubricCriterionListCreateAPIView.as_view(),
        name="rubric-criterion-list-create",
    ),
    path(
        "criteria/<int:pk>/",
        RubricCriterionDetailAPIView.as_view(),
        name="rubric-criterion-detail",
    ),
    path(
        "rubrics/<int:rubric_id>/criteria/reorder/",
        RubricCriteriaReorderAPIView.as_view(),
        name="rubric-criteria-reorder",
    ),

    path(
        "grades/",
        GradeRecordListAPIView.as_view(),
        name="grade-list",
    ),
    path(
        "grades/<int:pk>/",
        GradeRecordDetailAPIView.as_view(),
        name="grade-detail",
    ),
    path(
        "submissions/<int:submission_id>/grade/",
        GradeRecordCreateFromSubmissionAPIView.as_view(),
        name="grade-create-from-submission",
    ),

    # Совместимость со старыми именами.
    path(
        "grade-records/",
        GradeRecordListAPIView.as_view(),
        name="grade-record-list",
    ),
    path(
        "grade-records/<int:pk>/",
        GradeRecordDetailAPIView.as_view(),
        name="grade-record-detail",
    ),
    path(
        "submissions/<int:submission_id>/grade-record/",
        GradeRecordCreateFromSubmissionAPIView.as_view(),
        name="grade-record-create-from-submission",
    ),

    path(
        "analytics/assignments/<int:assignment_id>/statistics/",
        AssignmentStatisticsAPIView.as_view(),
        name="assignment-statistics",
    ),
    path(
        "analytics/publications/<int:publication_id>/statistics/",
        PublicationStatisticsAPIView.as_view(),
        name="publication-statistics",
    ),
    path(
        "analytics/assignments/<int:assignment_id>/students/<int:student_id>/progress/",
        StudentAssignmentProgressAPIView.as_view(),
        name="student-assignment-progress",
    ),
    path(
        "analytics/courses/<int:course_id>/dashboard/",
        CourseAssignmentDashboardAPIView.as_view(),
        name="course-assignment-dashboard",
    ),
]
