# Generated by Django 6.0.4 on 2026-04-22 09:35

import apps.feedback.models.feedback_attachment
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('question', 'Вопрос'), ('suggestion', 'Предложение'), ('bug', 'Сообщение об ошибке'), ('complaint', 'Жалоба'), ('cooperation', 'Сотрудничество'), ('callback', 'Обратный звонок'), ('other', 'Другое')], default='question', max_length=32, verbose_name='Тип обращения')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('waiting_for_user', 'Ожидает ответа пользователя'), ('resolved', 'Решено'), ('rejected', 'Отклонено'), ('spam', 'Спам'), ('archived', 'Архивировано')], default='new', max_length=32, verbose_name='Статус')),
                ('source', models.CharField(choices=[('contacts_page', 'Страница контактов'), ('error_modal', 'Модальное окно ошибки'), ('support_widget', 'Виджет поддержки'), ('footer', 'Футер'), ('admin_panel', 'Админ-панель'), ('api', 'API'), ('other', 'Другое')], default='contacts_page', max_length=32, verbose_name='Источник')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Сообщение')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Имя отправителя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email отправителя')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон отправителя')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name='Организация')),
                ('is_personal_data_consent', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('personal_data_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на обработку персональных данных')),
                ('page_url', models.URLField(blank=True, verbose_name='URL страницы')),
                ('frontend_route', models.CharField(blank=True, max_length=255, verbose_name='Маршрут фронтенда')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='Код ошибки')),
                ('error_title', models.CharField(blank=True, max_length=255, verbose_name='Краткий заголовок ошибки')),
                ('error_details', models.TextField(blank=True, verbose_name='Технические детали ошибки')),
                ('client_platform', models.CharField(blank=True, max_length=100, verbose_name='Платформа клиента')),
                ('app_version', models.CharField(blank=True, max_length=100, verbose_name='Версия приложения')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('reply_message', models.TextField(blank=True, verbose_name='Комментарий / ответ')),
                ('internal_note', models.TextField(blank=True, verbose_name='Внутренняя заметка')),
                ('is_spam_suspected', models.BooleanField(default=False, verbose_name='Подозрение на спам')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('referrer', models.URLField(blank=True, verbose_name='Referrer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_feedback_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'db_table': 'feedback_request',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.feedback.models.feedback_attachment.feedback_attachment_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('pdf', 'PDF'), ('doc', 'DOC / DOCX'), ('other', 'Другое')], default='other', max_length=16, verbose_name='Тип файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла в байтах')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('feedback_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedbackrequest', verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Вложение обращения',
                'verbose_name_plural': 'Вложения обращений',
                'db_table': 'feedback_attachment',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='feedbackrequest',
            index=models.Index(fields=['status', 'created_at'], name='feedback_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequest',
            index=models.Index(fields=['type', 'created_at'], name='feedback_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequest',
            index=models.Index(fields=['source', 'created_at'], name='feedback_source_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequest',
            index=models.Index(fields=['email'], name='feedback_email_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequest',
            index=models.Index(fields=['created_at'], name='feedback_created_idx'),
        ),
    ]
