# Generated by Django 6.0.4 on 2026-04-22 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequestContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Контактные данные обращения',
                'verbose_name_plural': 'Контактные данные обращений',
                'db_table': 'feedback_request_contact',
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequestProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата назначения')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('reply_message', models.TextField(blank=True, verbose_name='Ответ пользователю')),
                ('internal_note', models.TextField(blank=True, verbose_name='Внутренняя заметка')),
                ('is_spam_suspected', models.BooleanField(default=False, verbose_name='Подозрение на спам')),
            ],
            options={
                'verbose_name': 'Обработка обращения',
                'verbose_name_plural': 'Обработка обращений',
                'db_table': 'feedback_request_processing',
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequestTechnical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('page_url', models.URLField(blank=True, max_length=500, verbose_name='URL страницы')),
                ('frontend_route', models.CharField(blank=True, max_length=255, verbose_name='Frontend route')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='Код ошибки')),
                ('error_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок ошибки')),
                ('error_details', models.TextField(blank=True, verbose_name='Детали ошибки')),
                ('client_platform', models.CharField(blank=True, max_length=100, verbose_name='Клиентская платформа')),
                ('app_version', models.CharField(blank=True, max_length=100, verbose_name='Версия приложения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Referrer')),
                ('extra_payload', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные технические данные')),
            ],
            options={
                'verbose_name': 'Технический контекст обращения',
                'verbose_name_plural': 'Технические контексты обращений',
                'db_table': 'feedback_request_technical',
            },
        ),
        migrations.CreateModel(
            name='FeedbackStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32, verbose_name='Предыдущий статус')),
                ('to_status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('waiting_user', 'Ожидает пользователя'), ('resolved', 'Решено'), ('rejected', 'Отклонено'), ('spam', 'Спам'), ('archived', 'В архиве')], max_length=32, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'История статуса обращения',
                'verbose_name_plural': 'История статусов обращений',
                'db_table': 'feedback_status_history',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='feedbackattachment',
            options={'verbose_name': 'Вложение обращения', 'verbose_name_plural': 'Вложения обращений'},
        ),
        migrations.RemoveIndex(
            model_name='feedbackrequest',
            name='feedback_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedbackrequest',
            name='feedback_created_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackrequest',
            new_name='feedback_re_status_ecd03b_idx',
            old_name='feedback_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackrequest',
            new_name='feedback_re_type_1b205b_idx',
            old_name='feedback_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackrequest',
            new_name='feedback_re_source_c7fcc1_idx',
            old_name='feedback_source_created_idx',
        ),
        migrations.RemoveField(
            model_name='feedbackattachment',
            name='file_type',
        ),
        migrations.AddField(
            model_name='feedbackattachment',
            name='kind',
            field=models.CharField(choices=[('image', 'Изображение'), ('pdf', 'PDF'), ('document', 'Документ'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Тип файла'),
        ),
        migrations.AddField(
            model_name='feedbackattachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='MIME-тип'),
        ),
        migrations.AddField(
            model_name='feedbackattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='feedbackattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='feedbackattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='source',
            field=models.CharField(choices=[('contacts_page', 'Страница контактов'), ('error_modal', 'Модальное окно ошибки'), ('course_page', 'Страница курса'), ('profile_page', 'Страница профиля'), ('other', 'Другое')], db_index=True, default='contacts_page', max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('waiting_user', 'Ожидает пользователя'), ('resolved', 'Решено'), ('rejected', 'Отклонено'), ('spam', 'Спам'), ('archived', 'В архиве')], db_index=True, default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='type',
            field=models.CharField(choices=[('question', 'Вопрос'), ('bug', 'Ошибка'), ('idea', 'Идея'), ('complaint', 'Жалоба'), ('access', 'Доступ'), ('technical', 'Техническое обращение'), ('other', 'Другое')], db_index=True, default='question', max_length=32, verbose_name='Тип обращения'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddIndex(
            model_name='feedbackattachment',
            index=models.Index(fields=['feedback_request', 'created_at'], name='feedback_at_feedbac_fda5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackattachment',
            index=models.Index(fields=['kind'], name='feedback_at_kind_4dd132_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequest',
            index=models.Index(fields=['user', 'created_at'], name='feedback_re_user_id_418eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequest',
            index=models.Index(fields=['status', 'type'], name='feedback_re_status_12ab17_idx'),
        ),
        migrations.AddField(
            model_name='feedbackrequestcontact',
            name='feedback_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='feedback.feedbackrequest', verbose_name='Обращение'),
        ),
        migrations.AddField(
            model_name='feedbackrequestprocessing',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback_requests', to=settings.AUTH_USER_MODEL, verbose_name='Назначено на'),
        ),
        migrations.AddField(
            model_name='feedbackrequestprocessing',
            name='feedback_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='feedback.feedbackrequest', verbose_name='Обращение'),
        ),
        migrations.AddField(
            model_name='feedbackrequestprocessing',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_feedback_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обработано пользователем'),
        ),
        migrations.AddField(
            model_name='feedbackrequesttechnical',
            name='feedback_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical', to='feedback.feedbackrequest', verbose_name='Обращение'),
        ),
        migrations.AddField(
            model_name='feedbackstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='feedbackstatushistory',
            name='feedback_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='feedback.feedbackrequest', verbose_name='Обращение'),
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='client_platform',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='error_code',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='error_details',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='error_title',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='frontend_route',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='internal_note',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='is_spam_suspected',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='page_url',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='reply_message',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='user_agent',
        ),
        migrations.AddIndex(
            model_name='feedbackrequestprocessing',
            index=models.Index(fields=['assigned_to'], name='feedback_re_assigne_a9f597_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequestprocessing',
            index=models.Index(fields=['processed_by'], name='feedback_re_process_02768a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequestprocessing',
            index=models.Index(fields=['processed_at'], name='feedback_re_process_4e0a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequestprocessing',
            index=models.Index(fields=['is_spam_suspected'], name='feedback_re_is_spam_1f8d94_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequesttechnical',
            index=models.Index(fields=['error_code'], name='feedback_re_error_c_e9979c_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequesttechnical',
            index=models.Index(fields=['client_platform'], name='feedback_re_client__00e819_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackstatushistory',
            index=models.Index(fields=['feedback_request', 'created_at'], name='feedback_st_feedbac_1c41ea_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackstatushistory',
            index=models.Index(fields=['to_status', 'created_at'], name='feedback_st_to_stat_0cb7db_idx'),
        ),
    ]
