# Generated by Django 6.0.4 on 2026-04-23 16:39

import apps.course.models.course
import apps.course.models.material
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0002_rename_самостоятельная_работа_curriculumitem_independent_hours'),
        ('organizations', '0002_alter_groupcurator_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Код курса')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('course_type', models.CharField(choices=[('academic', 'Учебный курс'), ('author', 'Авторский курс'), ('exam_prep', 'Подготовка к экзамену'), ('intensive', 'Интенсив'), ('club', 'Клуб / факультатив')], default='author', max_length=32, verbose_name='Тип курса')),
                ('origin', models.CharField(choices=[('manual', 'Создан вручную'), ('group_subject', 'На основе учебного контура'), ('template', 'На основе шаблона'), ('import', 'Импорт')], default='manual', max_length=32, verbose_name='Источник')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архив')], default='draft', max_length=32, verbose_name='Статус')),
                ('visibility', models.CharField(choices=[('private', 'Приватный'), ('assigned_only', 'Только по назначению'), ('organization', 'Внутри организации'), ('public_link', 'По публичной ссылке')], default='assigned_only', max_length=32, verbose_name='Видимость')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('basic', 'Базовый'), ('advanced', 'Продвинутый'), ('exam', 'Экзаменационный')], default='basic', max_length=32, verbose_name='Уровень')),
                ('language', models.CharField(default='ru', max_length=12, verbose_name='Язык')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.course.models.course.course_cover_upload_to, verbose_name='Обложка')),
                ('is_template', models.BooleanField(default=False, verbose_name='Шаблон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('allow_self_enrollment', models.BooleanField(default=False, verbose_name='Разрешить самостоятельную запись')),
                ('enrollment_code', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Код записи')),
                ('estimated_minutes', models.PositiveIntegerField(default=0, verbose_name='Плановая длительность (мин)')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='education.academicyear', verbose_name='Учебный год')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('group_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='education.groupsubject', verbose_name='Связь с учебным предметом группы')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='organizations.organization', verbose_name='Организация')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='education.educationperiod', verbose_name='Учебный период')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='organizations.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'course',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assignment_type', models.CharField(choices=[('group', 'Назначение группе'), ('student', 'Назначение студенту')], max_length=16, verbose_name='Тип назначения')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Доступ с')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Доступ до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('auto_enroll', models.BooleanField(default=True, verbose_name='Автоматически зачислять')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course.course', verbose_name='Курс')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='organizations.group', verbose_name='Группа')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Назначение курса',
                'verbose_name_plural': 'Назначения курса',
                'db_table': 'course_assignment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('enrolled', 'Зачислен'), ('in_progress', 'Проходит'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('archived', 'Архив')], default='enrolled', max_length=24, verbose_name='Статус')),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата зачисления')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс (%)')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='course.courseassignment', verbose_name='Назначение')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Записи на курс',
                'db_table': 'course_enrollment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('lesson_type', models.CharField(choices=[('video', 'Видео'), ('text', 'Текстовый урок'), ('practice', 'Практика'), ('test', 'Тест'), ('homework', 'Домашняя работа'), ('webinar', 'Вебинар / занятие'), ('file', 'Файл / материал'), ('link', 'Ссылка')], default='text', max_length=32, verbose_name='Тип урока')),
                ('estimated_minutes', models.PositiveIntegerField(default=0, verbose_name='Плановая длительность (мин)')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Доступен в превью')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='Доступен с')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('external_url', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок курса',
                'verbose_name_plural': 'Уроки курса',
                'db_table': 'course_lesson',
                'ordering': ('module', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('material_type', models.CharField(choices=[('file', 'Файл'), ('link', 'Ссылка'), ('image', 'Изображение'), ('presentation', 'Презентация'), ('document', 'Документ'), ('archive', 'Архив'), ('other', 'Другое')], default='file', max_length=32, verbose_name='Тип материала')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.course.models.material.course_material_upload_to, verbose_name='Файл')),
                ('external_url', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('is_downloadable', models.BooleanField(default=True, verbose_name='Можно скачать')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Виден пользователю')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course.course', verbose_name='Курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course.courselesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Материал курса',
                'verbose_name_plural': 'Материалы курса',
                'db_table': 'course_material',
                'ordering': ('course', 'lesson', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('estimated_minutes', models.PositiveIntegerField(default=0, verbose_name='Плановая длительность (мин)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль курса',
                'verbose_name_plural': 'Модули курса',
                'db_table': 'course_module',
                'ordering': ('course', 'order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='courselesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.coursemodule', verbose_name='Модуль'),
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('total_lessons_count', models.PositiveIntegerField(default=0, verbose_name='Всего уроков')),
                ('completed_lessons_count', models.PositiveIntegerField(default=0, verbose_name='Завершено уроков')),
                ('required_lessons_count', models.PositiveIntegerField(default=0, verbose_name='Обязательных уроков')),
                ('completed_required_lessons_count', models.PositiveIntegerField(default=0, verbose_name='Завершено обязательных уроков')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс (%)')),
                ('spent_minutes', models.PositiveIntegerField(default=0, verbose_name='Потрачено минут')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='course.courseenrollment', verbose_name='Запись на курс')),
                ('last_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_progress_entries', to='course.courselesson', verbose_name='Последний урок')),
            ],
            options={
                'verbose_name': 'Прогресс по курсу',
                'verbose_name_plural': 'Прогресс по курсам',
                'db_table': 'course_progress',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('teacher', 'Преподаватель'), ('methodist', 'Методист'), ('assistant', 'Ассистент')], default='teacher', max_length=32, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('can_edit', models.BooleanField(default=True, verbose_name='Может редактировать курс')),
                ('can_manage_structure', models.BooleanField(default=True, verbose_name='Может управлять структурой')),
                ('can_manage_assignments', models.BooleanField(default=False, verbose_name='Может назначать курс')),
                ('can_view_analytics', models.BooleanField(default=True, verbose_name='Может смотреть аналитику')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначен')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teachers', to='course.course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher_links', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Преподаватель курса',
                'verbose_name_plural': 'Преподаватели курса',
                'db_table': 'course_teacher',
                'ordering': ('course', 'teacher'),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_courses', through='course.CourseTeacher', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('skipped', 'Пропущен')], default='not_started', max_length=24, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний просмотр')),
                ('spent_minutes', models.PositiveIntegerField(default=0, verbose_name='Потрачено минут')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Баллы / результат')),
                ('course_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to='course.courseprogress', verbose_name='Прогресс по курсу')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to='course.courseenrollment', verbose_name='Запись на курс')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to='course.courselesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Прогресс по уроку',
                'verbose_name_plural': 'Прогресс по урокам',
                'db_table': 'lesson_progress',
                'ordering': ('lesson', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['course', 'is_active'], name='course_assi_course__935bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['group'], name='course_assi_group_i_b148bd_idx'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['student'], name='course_assi_student_441a37_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('course', 'group'), name='unique_course_group_assignment'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('course', 'student'), name='unique_course_student_assignment'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', 'status'], name='course_enro_course__bcaa77_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['student', 'status'], name='course_enro_student_ba5c22_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='unique_course_student_enrollment'),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['course'], name='course_mate_course__e62329_idx'),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['lesson'], name='course_mate_lesson__231aec_idx'),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['material_type'], name='course_mate_materia_c364a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_course_module_order'),
        ),
        migrations.AddIndex(
            model_name='courselesson',
            index=models.Index(fields=['course', 'lesson_type'], name='course_less_course__66d42e_idx'),
        ),
        migrations.AddIndex(
            model_name='courselesson',
            index=models.Index(fields=['module', 'is_published'], name='course_less_module__a6bd12_idx'),
        ),
        migrations.AddConstraint(
            model_name='courselesson',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_course_lesson_order'),
        ),
        migrations.AddConstraint(
            model_name='courseteacher',
            constraint=models.UniqueConstraint(fields=('course', 'teacher'), name='unique_course_teacher'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='course_status_7f657c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['visibility'], name='course_visibil_9fb8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type'], name='course_course__9e4d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['author'], name='course_author__a61939_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['organization'], name='course_organiz_cc790d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject'], name='course_subject_e9da55_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['academic_year'], name='course_academi_2c9bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'status'], name='lesson_prog_lesson__4ce257_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'status'], name='lesson_prog_enrollm_072990_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson'), name='unique_enrollment_lesson_progress'),
        ),
    ]
