# Generated by Django 6.0.3 on 2026-04-19 21:35

import apps.education.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: 2025/2026', max_length=32, unique=True, validators=[apps.education.validators.validate_academic_year_name], verbose_name='Наименование учебного года')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий учебный год')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные годы',
                'db_table': 'education_academic_year',
                'ordering': ('-start_date',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_current_academic_year')],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Код учебного плана')),
                ('name', models.CharField(max_length=255, verbose_name='Название учебного плана')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общее количество часов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='education.academicyear', verbose_name='Учебный год')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curricula', to='organizations.department', verbose_name='Подразделение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'db_table': 'education_curriculum',
                'ordering': ('organization', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EducationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название периода')),
                ('code', models.CharField(max_length=64, validators=[apps.education.validators.validate_period_code], verbose_name='Код периода')),
                ('period_type', models.CharField(choices=[('year', 'Год'), ('semester', 'Семестр'), ('trimester', 'Триместр'), ('quarter', 'Четверть'), ('module', 'Модуль'), ('other', 'Иной')], default='semester', max_length=32, verbose_name='Тип периода')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий период')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='education.academicyear', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Учебный период',
                'verbose_name_plural': 'Учебные периоды',
                'db_table': 'education_period',
                'ordering': ('academic_year', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='CurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер')),
                ('planned_hours', models.PositiveIntegerField(default=0, verbose_name='Плановые часы')),
                ('contact_hours', models.PositiveIntegerField(default=0, verbose_name='Контактные часы')),
                ('самостоятельная_работа', models.PositiveIntegerField(default=0, verbose_name='Самостоятельная работа')),
                ('assessment_type', models.CharField(choices=[('none', 'Без аттестации'), ('pass_fail', 'Зачет / незачет'), ('credit', 'Зачет'), ('exam', 'Экзамен'), ('test', 'Тестирование'), ('project', 'Проект'), ('other', 'Иная форма')], default='none', max_length=32, verbose_name='Форма аттестации')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный элемент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='education.curriculum', verbose_name='Учебный план')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_items', to='organizations.subject', verbose_name='Предмет')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_items', to='education.educationperiod', verbose_name='Учебный период')),
            ],
            options={
                'verbose_name': 'Элемент учебного плана',
                'verbose_name_plural': 'Элементы учебного плана',
                'db_table': 'education_curriculum_item',
                'ordering': ('curriculum', 'period__sequence', 'sequence', 'subject'),
            },
        ),
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_hours', models.PositiveIntegerField(default=0, verbose_name='Плановые часы')),
                ('contact_hours', models.PositiveIntegerField(default=0, verbose_name='Контактные часы')),
                ('independent_hours', models.PositiveIntegerField(default=0, verbose_name='Самостоятельная работа')),
                ('assessment_type', models.CharField(choices=[('none', 'Без аттестации'), ('pass_fail', 'Зачет / незачет'), ('credit', 'Зачет'), ('exam', 'Экзамен'), ('test', 'Тестирование'), ('project', 'Проект'), ('other', 'Иная форма')], default='none', max_length=32, verbose_name='Форма аттестации')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный предмет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_subjects', to='education.academicyear', verbose_name='Учебный год')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subjects', to='organizations.group', verbose_name='Группа')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_subjects', to='education.educationperiod', verbose_name='Учебный период')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_subjects', to='organizations.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет группы',
                'verbose_name_plural': 'Предметы групп',
                'db_table': 'education_group_subject',
                'ordering': ('group', 'period__sequence', 'subject'),
            },
        ),
        migrations.CreateModel(
            name='StudentGroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Дата зачисления')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения / выбытия')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('transferred', 'Переведен'), ('suspended', 'Приостановлено'), ('graduated', 'Завершено'), ('expelled', 'Отчислен'), ('archived', 'Архивировано')], default='active', max_length=32, verbose_name='Статус')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Основное зачисление')),
                ('journal_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер в журнале')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='education.academicyear', verbose_name='Учебный год')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='organizations.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Зачисление студента в группу',
                'verbose_name_plural': 'Зачисления студентов в группы',
                'db_table': 'education_student_group_enrollment',
                'ordering': ('-academic_year__start_date', 'group', 'student'),
            },
        ),
        migrations.CreateModel(
            name='TeacherGroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Основной преподаватель'), ('assistant', 'Ассистент'), ('substitute', 'Замещающий преподаватель'), ('other', 'Иная роль')], default='primary', max_length=32, verbose_name='Роль преподавателя')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Основной преподаватель')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('planned_hours', models.PositiveIntegerField(default=0, verbose_name='Плановые часы преподавателя')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('group_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='education.groupsubject', verbose_name='Предмет группы')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_group_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Закрепление преподавателя за предметом группы',
                'verbose_name_plural': 'Закрепления преподавателей за предметами групп',
                'db_table': 'education_teacher_group_subject',
                'ordering': ('group_subject', 'teacher'),
            },
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('organization', 'academic_year', 'code'), name='unique_curriculum_code_per_organization_and_year'),
        ),
        migrations.AddConstraint(
            model_name='educationperiod',
            constraint=models.UniqueConstraint(fields=('academic_year', 'code'), name='unique_period_code_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='educationperiod',
            constraint=models.UniqueConstraint(fields=('academic_year', 'sequence'), name='unique_period_sequence_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='educationperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('academic_year', 'is_current'), name='unique_current_period_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='curriculumitem',
            constraint=models.UniqueConstraint(fields=('curriculum', 'period', 'subject'), name='unique_subject_per_curriculum_period'),
        ),
        migrations.AddConstraint(
            model_name='curriculumitem',
            constraint=models.UniqueConstraint(fields=('curriculum', 'period', 'sequence'), name='unique_sequence_per_curriculum_period'),
        ),
        migrations.AddConstraint(
            model_name='groupsubject',
            constraint=models.UniqueConstraint(fields=('group', 'subject', 'academic_year', 'period'), name='unique_group_subject_per_period'),
        ),
        migrations.AddConstraint(
            model_name='studentgroupenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'group', 'academic_year'), name='unique_student_group_enrollment_per_year'),
        ),
        migrations.AddConstraint(
            model_name='studentgroupenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student', 'academic_year', 'is_primary'), name='unique_primary_student_enrollment_per_year'),
        ),
        migrations.AddConstraint(
            model_name='studentgroupenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('journal_number__isnull', False)), fields=('group', 'academic_year', 'journal_number'), name='unique_journal_number_per_group_and_year'),
        ),
        migrations.AddConstraint(
            model_name='teachergroupsubject',
            constraint=models.UniqueConstraint(fields=('teacher', 'group_subject'), name='unique_teacher_group_subject_assignment'),
        ),
        migrations.AddConstraint(
            model_name='teachergroupsubject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('group_subject', 'is_primary'), name='unique_primary_teacher_per_group_subject'),
        ),
    ]
