# Generated by Django 6.0.3 on 2026-04-19 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculumitem',
            old_name='самостоятельная_работа',
            new_name='independent_hours',
        ),
    ]
