# Generated by Django 6.0.4 on 2026-04-28 18:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('course', '0001_initial'),
        ('organizations', '0002_alter_groupcurator_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('started_at', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('ended_at', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('planned_topic', models.CharField(blank=True, max_length=512, verbose_name='Плановая тема')),
                ('actual_topic', models.CharField(blank=True, max_length=512, verbose_name='Фактическая тема')),
                ('homework', models.TextField(blank=True, verbose_name='Домашнее задание')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('conducted', 'Проведено'), ('cancelled', 'Отменено'), ('postponed', 'Перенесено'), ('replaced', 'Замена')], db_index=True, default='planned', max_length=20, verbose_name='Статус')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('lesson_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер занятия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lessons', to='course.course', verbose_name='Курс')),
                ('course_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lessons', to='course.courselesson', verbose_name='Урок курса (КТП)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lessons', to='organizations.group', verbose_name='Учебная группа')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие журнала',
                'verbose_name_plural': 'Занятия журнала',
                'db_table': 'journal_lesson',
                'ordering': ['date', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('current', 'Текущая'), ('control', 'Контрольная работа'), ('test', 'Тест'), ('practical', 'Практическая работа'), ('lab', 'Лабораторная работа'), ('homework', 'Домашняя работа'), ('exam', 'Экзамен'), ('credit', 'Зачёт'), ('midterm', 'Промежуточная аттестация'), ('final', 'Итоговая оценка'), ('manual', 'Ручная оценка')], db_index=True, default='current', max_length=30, verbose_name='Тип оценки')),
                ('scale', models.CharField(choices=[('five_point', 'Пятибалльная'), ('pass_fail', 'Зачёт/незачёт'), ('points', 'Баллы'), ('percent', 'Проценты')], default='five_point', max_length=20, verbose_name='Шкала')),
                ('score_five', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (5-балльная)')),
                ('score_points', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баллы')),
                ('max_points', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимум баллов')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='Зачтено')),
                ('weight', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Вес оценки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('is_auto', models.BooleanField(default=False, verbose_name='Выставлена автоматически')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('grade_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_grades', to='assignments.graderecord', verbose_name='Запись оценки (assignments)')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_journal_grades', to=settings.AUTH_USER_MODEL, verbose_name='Выставил')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_grades', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_grades', to='assignments.submission', verbose_name='Сдача задания')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.journallesson', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Оценка в журнале',
                'verbose_name_plural': 'Оценки в журнале',
                'db_table': 'journal_grade',
                'ordering': ['lesson__date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('late', 'Опоздал'), ('excused', 'Уважительная причина'), ('remote', 'Дистанционно')], db_index=True, default='present', max_length=20, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=512, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='journal.journallesson', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Запись посещаемости',
                'verbose_name_plural': 'Записи посещаемости',
                'db_table': 'journal_attendance_record',
                'ordering': ['lesson__date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='JournalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons', models.PositiveSmallIntegerField(default=0, verbose_name='Всего занятий')),
                ('attended_lessons', models.PositiveSmallIntegerField(default=0, verbose_name='Посещено занятий')),
                ('absent_lessons', models.PositiveSmallIntegerField(default=0, verbose_name='Пропущено занятий')),
                ('attendance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Посещаемость (%)')),
                ('avg_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Средний балл')),
                ('debt_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество задолженностей')),
                ('total_topics', models.PositiveSmallIntegerField(default=0, verbose_name='Всего тем')),
                ('completed_topics', models.PositiveSmallIntegerField(default=0, verbose_name='Пройдено тем')),
                ('topics_behind', models.PositiveSmallIntegerField(default=0, verbose_name='Тем в отставании')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Прогресс по курсу (%)')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Последний пересчёт')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_summaries', to='course.course', verbose_name='Курс')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_summaries', to='organizations.group', verbose_name='Учебная группа')),
                ('student', models.ForeignKey(blank=True, help_text='Если не задан — это агрегат по группе', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Сводка журнала',
                'verbose_name_plural': 'Сводки журнала',
                'db_table': 'journal_summary',
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('status', models.CharField(choices=[('planned', 'По плану'), ('completed', 'Пройдено'), ('postponed', 'Перенесено'), ('skipped', 'Пропущено'), ('behind', 'Отставание')], db_index=True, default='planned', max_length=20, verbose_name='Статус')),
                ('days_behind', models.SmallIntegerField(default=0, help_text='Положительное — отставание, отрицательное — опережение', verbose_name='Отставание (дней)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress_records', to='course.course', verbose_name='Курс')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress_records', to='organizations.group', verbose_name='Учебная группа')),
                ('journal_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_progress_records', to='journal.journallesson', verbose_name='Занятие журнала')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress_records', to='course.courselesson', verbose_name='Урок курса (КТП)')),
            ],
            options={
                'verbose_name': 'Прогресс темы',
                'verbose_name_plural': 'Прогресс тем',
                'db_table': 'journal_topic_progress',
                'ordering': ['planned_date', 'lesson'],
            },
        ),
        migrations.AddIndex(
            model_name='journallesson',
            index=models.Index(fields=['course', 'group', 'date'], name='idx_jlesson_course_group_date'),
        ),
        migrations.AddIndex(
            model_name='journallesson',
            index=models.Index(fields=['teacher', 'date'], name='idx_jlesson_teacher_date'),
        ),
        migrations.AddIndex(
            model_name='journallesson',
            index=models.Index(fields=['status'], name='idx_jlesson_status'),
        ),
        migrations.AddConstraint(
            model_name='journallesson',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson_number__isnull', False)), fields=('course', 'group', 'date', 'lesson_number'), name='uniq_jlesson_course_group_date_num'),
        ),
        migrations.AddIndex(
            model_name='journalgrade',
            index=models.Index(fields=['lesson', 'student'], name='idx_jgrade_lesson_student'),
        ),
        migrations.AddIndex(
            model_name='journalgrade',
            index=models.Index(fields=['student', 'grade_type'], name='idx_jgrade_student_type'),
        ),
        migrations.AddIndex(
            model_name='journalgrade',
            index=models.Index(fields=['grade_type'], name='idx_jgrade_type'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['lesson', 'status'], name='idx_attend_lesson_status'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'status'], name='idx_attend_student_status'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('lesson', 'student'), name='uniq_attend_lesson_student'),
        ),
        migrations.AddIndex(
            model_name='journalsummary',
            index=models.Index(fields=['course', 'group'], name='idx_jsummary_course_group'),
        ),
        migrations.AddIndex(
            model_name='journalsummary',
            index=models.Index(fields=['student'], name='idx_jsummary_student'),
        ),
        migrations.AddConstraint(
            model_name='journalsummary',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('course', 'group', 'student'), name='uniq_jsummary_course_group_student'),
        ),
        migrations.AddConstraint(
            model_name='journalsummary',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', True)), fields=('course', 'group'), name='uniq_jsummary_course_group_no_student'),
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['course', 'group'], name='idx_tprogress_course_group'),
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['status'], name='idx_tprogress_status'),
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['group', 'status'], name='idx_tprogress_group_status'),
        ),
        migrations.AddConstraint(
            model_name='topicprogress',
            constraint=models.UniqueConstraint(fields=('course', 'group', 'lesson'), name='uniq_topic_progress_course_group_lesson'),
        ),
    ]
