# Generated by Django 5.0.7 on 2026-05-02 14:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('course', '0001_initial'),
        ('journal', '0001_initial'),
        ('organizations', '0002_alter_groupcurator_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['lesson', 'student'], 'verbose_name': 'Запись посещаемости', 'verbose_name_plural': 'Посещаемость'},
        ),
        migrations.AlterModelOptions(
            name='journalgrade',
            options={'ordering': ['-lesson__date', 'student', 'grade_type', 'id'], 'verbose_name': 'Оценка журнала', 'verbose_name_plural': 'Оценки журнала'},
        ),
        migrations.AlterModelOptions(
            name='journallesson',
            options={'ordering': ['-date', 'lesson_number', 'id'], 'verbose_name': 'Занятие журнала', 'verbose_name_plural': 'Занятия журнала'},
        ),
        migrations.AlterModelOptions(
            name='journalsummary',
            options={'ordering': ['course', 'group', 'student_id'], 'verbose_name': 'Сводка журнала', 'verbose_name_plural': 'Сводки журнала'},
        ),
        migrations.AlterModelOptions(
            name='topicprogress',
            options={'ordering': ['course', 'group', 'lesson__order', 'id'], 'verbose_name': 'Прогресс по теме', 'verbose_name_plural': 'Прогресс по темам'},
        ),
        migrations.RemoveField(
            model_name='journalgrade',
            name='max_points',
        ),
        migrations.RemoveField(
            model_name='journalgrade',
            name='score_points',
        ),
        migrations.AddField(
            model_name='journalsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('late', 'Опоздал'), ('excused', 'Отсутствовал по уважительной причине'), ('remote', 'Присутствовал дистанционно')], db_index=True, default='present', max_length=20, verbose_name='Статус посещаемости'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='journalgrade',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='journalgrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='journalgrade',
            name='grade_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_grades', to='assignments.graderecord', verbose_name='Запись оценки из модуля заданий'),
        ),
        migrations.AlterField(
            model_name='journalgrade',
            name='grade_type',
            field=models.CharField(choices=[('current', 'Текущая'), ('homework', 'Домашняя работа'), ('test', 'Тест'), ('practical', 'Практическая работа'), ('laboratory', 'Лабораторная работа'), ('control', 'Контрольная работа'), ('exam', 'Экзамен'), ('credit', 'Зачёт'), ('final', 'Итоговая')], db_index=True, default='current', max_length=30, verbose_name='Тип оценки'),
        ),
        migrations.AlterField(
            model_name='journalgrade',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_grades_given', to=settings.AUTH_USER_MODEL, verbose_name='Кем выставлена'),
        ),
        migrations.AlterField(
            model_name='journalgrade',
            name='is_auto',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Выставлена автоматически'),
        ),
        migrations.AlterField(
            model_name='journalgrade',
            name='is_passed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Зачёт получен'),
        ),
        migrations.AlterField(
            model_name='journalgrade',
            name='scale',
            field=models.CharField(choices=[('five_point', 'Пятибалльная'), ('pass_fail', 'Зачёт/незачёт')], default='five_point', max_length=20, verbose_name='Шкала оценивания'),
        ),
        migrations.AlterField(
            model_name='journalgrade',
            name='score_five',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка от 1 до 5'),
        ),
        migrations.AlterField(
            model_name='journalgrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='journallesson',
            name='course_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lessons', to='course.courselesson', verbose_name='Плановая тема курса'),
        ),
        migrations.AlterField(
            model_name='journallesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='journallesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lessons', to='organizations.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='journallesson',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер занятия в дне'),
        ),
        migrations.AlterField(
            model_name='journallesson',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('rescheduled', 'Перенесено')], db_index=True, default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='journallesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lessons_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='journallesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='journalsummary',
            name='attendance_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Процент посещаемости'),
        ),
        migrations.AlterField(
            model_name='journalsummary',
            name='avg_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Средний балл'),
        ),
        migrations.AlterField(
            model_name='journalsummary',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата пересчёта'),
        ),
        migrations.AlterField(
            model_name='journalsummary',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_summaries', to='organizations.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='journalsummary',
            name='progress_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Процент прохождения программы'),
        ),
        migrations.AlterField(
            model_name='journalsummary',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='journalsummary',
            name='topics_behind',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Тем с отставанием'),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_topic_progress', to='course.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='days_behind',
            field=models.SmallIntegerField(default=0, verbose_name='Дней отставания'),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_topic_progress', to='organizations.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='journal_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_progress_records', to='journal.journallesson', verbose_name='Фактическое занятие'),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_topic_progress', to='course.courselesson', verbose_name='Плановая тема'),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('in_progress', 'В процессе'), ('completed', 'Пройдена'), ('skipped', 'Пропущена'), ('behind', 'Отставание')], db_index=True, default='planned', max_length=20, verbose_name='Статус прохождения'),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='journalgrade',
            index=models.Index(fields=['scale'], name='idx_jgrade_scale'),
        ),
        migrations.AddIndex(
            model_name='journalgrade',
            index=models.Index(fields=['is_auto'], name='idx_jgrade_is_auto'),
        ),
        migrations.AddConstraint(
            model_name='journalgrade',
            constraint=models.CheckConstraint(check=models.Q(('score_five__isnull', True), models.Q(('score_five__gte', 1), ('score_five__lte', 5)), _connector='OR'), name='chk_jgrade_score_five_range'),
        ),
        migrations.AddConstraint(
            model_name='journalgrade',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_passed__isnull', True), ('scale', 'five_point'), ('score_five__isnull', False)), models.Q(('is_passed__isnull', False), ('scale', 'pass_fail'), ('score_five__isnull', True)), _connector='OR'), name='chk_jgrade_scale_value_consistency'),
        ),
        migrations.AddConstraint(
            model_name='journalgrade',
            constraint=models.UniqueConstraint(condition=models.Q(('submission__isnull', False)), fields=('submission',), name='uniq_journal_grade_submission'),
        ),
        migrations.AddConstraint(
            model_name='journalgrade',
            constraint=models.UniqueConstraint(condition=models.Q(('grade_record__isnull', False)), fields=('grade_record',), name='uniq_journal_grade_record'),
        ),
    ]
