# Generated by Django 5.0.7 on 2026-05-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал без уважительной причины'), ('late', 'Опоздал'), ('excused', 'Отсутствовал по уважительной причине'), ('remote', 'Присутствовал дистанционно')], db_index=True, default='present', max_length=20, verbose_name='Статус посещаемости'),
        ),
        migrations.AlterField(
            model_name='journalgrade',
            name='grade_type',
            field=models.CharField(choices=[('current', 'Текущая'), ('classwork', 'Работа на занятии'), ('homework', 'Домашняя работа'), ('test', 'Тест'), ('practical', 'Практическая работа'), ('laboratory', 'Лабораторная работа'), ('control', 'Контрольная работа'), ('credit', 'Зачёт'), ('exam', 'Экзамен'), ('final', 'Итоговая')], db_index=True, default='current', max_length=30, verbose_name='Тип оценки'),
        ),
        migrations.AlterField(
            model_name='journallesson',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('rescheduled', 'Перенесено'), ('replaced', 'Замена')], db_index=True, default='planned', max_length=20, verbose_name='Статус'),
        ),
    ]
