# Generated by Django 5.0.7 on 2026-05-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_attendancerecord_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalgrade',
            name='grade_type',
            field=models.CharField(choices=[('current', 'Текущая'), ('classwork', 'Работа на занятии'), ('board_work', 'Работа у доски'), ('oral_answer', 'Устный ответ'), ('homework', 'Домашняя работа'), ('test', 'Тест'), ('quiz', 'Проверочная работа'), ('independent_work', 'Самостоятельная работа'), ('control_work', 'Контрольная работа'), ('practical_work', 'Практическая работа'), ('laboratory_work', 'Лабораторная работа'), ('project', 'Проектная работа'), ('credit', 'Зачёт'), ('exam', 'Экзамен'), ('final', 'Итоговая')], db_index=True, default='current', max_length=30, verbose_name='Тип оценки'),
        ),
    ]
