# Generated by Django 6.0.3 on 2026-04-19 20:04

import apps.organizations.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подразделения')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Краткое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'organizations_department',
                'ordering': ('organization', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Краткое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Образовательная организация',
                'verbose_name_plural': 'Образовательные организации',
                'db_table': 'organizations_organization',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Код типа организации')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип образовательной организации',
                'verbose_name_plural': 'Типы образовательных организаций',
                'db_table': 'organizations_organization_type',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Код категории')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория предметов',
                'verbose_name_plural': 'Категории предметов',
                'db_table': 'organizations_subject_category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('code', models.CharField(db_index=True, max_length=64, validators=[apps.organizations.validators.validate_group_code], verbose_name='Код группы')),
                ('study_form', models.CharField(choices=[('full_time', 'Очная'), ('part_time', 'Очно-заочная'), ('distance', 'Дистанционная'), ('extramural', 'Заочная'), ('other', 'Иная')], default='full_time', max_length=32, verbose_name='Форма обучения')),
                ('course_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс / год обучения')),
                ('admission_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год набора')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('academic_year', models.CharField(blank=True, help_text='Например: 2025/2026', max_length=32, validators=[apps.organizations.validators.validate_academic_year], verbose_name='Учебный год')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('archived', 'Архивирована'), ('graduated', 'Выпущена'), ('closed', 'Закрыта')], default='active', max_length=32, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='organizations.department', verbose_name='Подразделение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'db_table': 'organizations_group',
                'ordering': ('organization', 'name'),
            },
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organizations.organizationtype', verbose_name='Тип организации'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название предмета')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Краткое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='organizations.subjectcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Учебный предмет',
                'verbose_name_plural': 'Учебные предметы',
                'db_table': 'organizations_subject',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TeacherOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('main', 'Основное место работы'), ('part_time', 'Совместительство'), ('contract', 'Договор'), ('other', 'Иное')], default='main', max_length=32, verbose_name='Тип занятости')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная организация')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to='organizations.organization', verbose_name='Организация')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Связь преподавателя с организацией',
                'verbose_name_plural': 'Связи преподавателей с организациями',
                'db_table': 'organizations_teacher_organization',
                'ordering': ('organization', 'teacher'),
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной предмет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to='organizations.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Связь преподавателя с предметом',
                'verbose_name_plural': 'Связи преподавателей с предметами',
                'db_table': 'organizations_teacher_subject',
                'ordering': ('teacher', 'subject'),
            },
        ),
        migrations.CreateModel(
            name='GroupCurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Основной куратор')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curators', to='organizations.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_groups', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Куратор группы',
                'verbose_name_plural': 'Кураторы групп',
                'db_table': 'organizations_group_curator',
                'ordering': ('-is_primary', '-starts_at', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('group', 'teacher'), name='unique_teacher_per_group_curatorship')],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_group_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_group_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_department_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='teacherorganization',
            constraint=models.UniqueConstraint(fields=('teacher', 'organization'), name='unique_teacher_organization_link'),
        ),
        migrations.AddConstraint(
            model_name='teachersubject',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject'), name='unique_teacher_subject_link'),
        ),
    ]
