# Generated by Django 6.0.4 on 2026-04-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcurator',
            options={'ordering': ('-is_primary', '-is_active', '-starts_at', '-created_at'), 'verbose_name': 'Куратор группы', 'verbose_name_plural': 'Кураторы групп'},
        ),
        migrations.AddField(
            model_name='group',
            name='join_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код присоединения действует до'),
        ),
        migrations.AddField(
            model_name='group',
            name='join_code_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Хеш кода присоединения'),
        ),
        migrations.AddField(
            model_name='group',
            name='join_code_is_active',
            field=models.BooleanField(default=False, verbose_name='Код присоединения активен'),
        ),
        migrations.AddField(
            model_name='groupcurator',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='organization',
            name='teacher_registration_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код регистрации преподавателя действует до'),
        ),
        migrations.AddField(
            model_name='organization',
            name='teacher_registration_code_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Хеш кода регистрации преподавателя'),
        ),
        migrations.AddField(
            model_name='organization',
            name='teacher_registration_code_is_active',
            field=models.BooleanField(default=False, verbose_name='Код регистрации преподавателя активен'),
        ),
        migrations.AddField(
            model_name='teacherorganization',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
    ]
